[target.thumbv6m-none-eabi] # <-change for your platform
runner = 'probe-rs run --chip STM32C071rb' # <- change for your chip

[build]
target = "thumbv6m-none-eabi" # <-change for your platform

[env]
DEFMT_LOG = "trace" # <- can change to info, warn, or error
